---
title: "Model Evaluation and Optimization MNIST"
author: "Rick Scavetta"
output:
  html_document:
  fig_caption: true
  toc: true
  toc_float:
    collapsed: false
    smooth_scroll: false
  toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, eval = TRUE)

# Initialize packages
library(keras)
library(tidyverse)
```

# Session 2 {.tabset .tabset-fade .tabset-pills}

## Part 1: Data Preparation

## Obtain data

```{r data}
c(c(train_images, train_labels), c(test_images, test_labels)) %<-% dataset_mnist()
```

## View image

```{r plot}
digit <- train_images[1,,]
plot(as.raster(digit, max = 255))
```

## Normalize data:

```{r strImagesPre}
str(train_images)
str(test_images)
```

```{r normImages}
train_images <- array_reshape(train_images, c(60000, 28 * 28))
train_images <- train_images / 255
str(train_images)
```


```{r normImages}
test_images <- array_reshape(test_images, c(10000, 28 * 28))
test_images <- test_images / 255
str(test_images)
```

## Prepare labels:

```{r strLabelsPre}
train_labels_int <- train_labels
str(train_labels)

test_labels_int <- test_labels
str(test_labels)
```

```{r prepLabels}
train_labels <- to_categorical(train_labels)
test_labels <- to_categorical(test_labels)
```

```{r strLabelsPost}
str(train_labels)
str(test_labels)
```

# Part 2: Define Network

## Define the network

```{r architecture}
network <- keras_model_sequential() %>%
  layer_dense(units = 512, activation = "relu", input_shape = c(28 * 28)) %>%
  layer_dense(units = 10, activation = "softmax")
```

## View a summary of the network

```{r summary}
summary(network)
```

## Compile

```{r compile}
network %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)
```

## Train the model

```{r train}
history <- network %>% 
  fit(train_images, train_labels, epochs = 5, batch_size = 128)
```

## Plot progress

```{r plotTraining}
plot(history)
```

# Part 3: Check output

## Metrics

```{r metrics}
metrics <- network %>% evaluate(test_images, test_labels)
metrics

metrics$acc

# Error rate: incorrect calling
1 - metrics$acc

```

## Predictions

```{r predictions}
network %>% predict_classes(test_images[1:10,])
```

```{r allPredictions}
predictions <- network %>% predict_classes(test_images)

actual <- test_labels_int
totalmisses <- sum(predictions != actual)
```

# Confusion Matrix

```{r confusion, echo = F}
suppressPackageStartupMessages(library(tidyverse))

data.frame(target = test_labels_int,
                      prediction = network %>%
                        predict_classes(test_images)) %>% 
  filter(target != prediction) %>% 
  group_by(target, prediction) %>%
  count() %>%
  ungroup() %>%
  mutate(perc = n/nrow(.)*100) %>% 
  filter(n > 1) %>% 
  ggplot(aes(target, prediction, size = n)) +
  geom_point(shape = 15, col = "#9F92C6") +
  scale_x_continuous("Actual Target", breaks = 0:9) +
  scale_y_continuous("Prediction", breaks = 0:9) +
  scale_size_area(breaks = c(2,5,10,15), max_size = 5) +
  coord_fixed() +
  ggtitle(paste(totalmisses, "mismatches")) +
  theme_classic() +
  theme(rect = element_blank(),
        axis.line = element_blank(),
        axis.text = element_text(colour = "black"))

```

